### ISSUE TITLE
BUG | Line number not aligned

### ISSUE THREAD

**Issue by louisgv** [ift-gftc/doc.gdst#58]
## 🐛 Bug Report

**Describe the bug**
The line number of the code block does not align with the actual line itself.

**Screenshots**

![image](https://user-images.githubusercontent.com/6723574/79320650-feaf2a80-7ebe-11ea-8546-d1dd4abb5b50.png)

**Comment by louisgv** [comment]
Likely won't be able to easily fix this anytime soon. This is an issue with how prism.js generate the line number, and does not account for line-wrap. I spent a good hour investigating a way to fix this but couldn't find a clean solution.

**Comment by DuckScapePhilip** [comment]
Okay, I am going to close this if we can't fix this.
